# Generated by Django 5.0.4 on 2024-05-28 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('productType', models.CharField(choices=[('D', 'Drink'), ('B', 'Burguer')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='products-img/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refProduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='burguersrestapi.product')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orderDayHour', models.DateTimeField()),
                ('orderType', models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], default='P', max_length=1)),
                ('adress', models.CharField(max_length=100)),
                ('info', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='burguersrestapi.product')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refProduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='burguersrestapi.product')),
                ('ingredients', models.ManyToManyField(to='burguersrestapi.ingredient')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
