# Generated by Django 5.0.4 on 2024-05-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
