# Generated by Django 5.0.4 on 2024-05-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0003_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hour', models.CharField(max_length=50)),
                ('orderType', models.CharField(choices=[('D', 'D'), ('P', 'P')], default='P', max_length=1)),
                ('adress', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('productType', models.CharField(choices=[('D', 'D'), ('P', 'P')], max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='burger',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.AddField(
            model_name='burger',
            name='refProduct',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='burguersrestapi.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='refProduct',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='burguersrestapi.product'),
            preserve_default=False,
        ),
    ]
