# Generated by Django 5.0.4 on 2024-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0004_order_product_remove_burger_id_remove_drink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('D', 'Drink'), ('B', 'Burguer')], max_length=10),
        ),
    ]
