# Generated by Django 5.0.4 on 2024-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='burguersrestapi.product'),
        ),
    ]
