# Generated by Django 5.0.4 on 2024-05-13 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0007_alter_order_options_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hour',
        ),
        migrations.AddField(
            model_name='order',
            name='orderDayHour',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], default='P', max_length=1),
        ),
    ]
