# Generated by Django 5.0.4 on 2024-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0010_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burger',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
