# Generated by Django 5.0.4 on 2024-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguersrestapi', '0011_remove_burger_description_remove_drink_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
